import type { ActivitySourceValue, UserRoleValue } from '@/lib/types'
import type { Json } from '@/lib/types/json'

type DbActivityLog = {
  id: string
  actor_id: string | null
  actor_role: UserRoleValue | null
  source: ActivitySourceValue
  verb: string
  summary: string
  target_type: string
  target_id: string | null
  target_client_id: string | null
  target_project_id: string | null
  context_route: string | null
  metadata: Json
  created_at: string
  updated_at: string
  deleted_at: string | null
  restored_at: string | null
}

export type ActivityLogWithActor = DbActivityLog & {
  actor?: {
    id: string
    full_name: string | null
    email: string
    avatar_url: string | null
  } | null
}

export type ActivityTargetType =
  | 'TASK'
  | 'PROJECT'
  | 'CLIENT'
  | 'CONTACT'
  | 'LEAD'
  | 'SUBMISSION'
  | 'PROPOSAL'
  | 'COMMENT'
  | 'TIME_LOG'
  | 'HOUR_BLOCK'
  | 'INVOICE'
  | 'MONTHLY_CLOSE'
  | 'USER'
  | 'SETTINGS'
  | 'GENERAL'

export const ActivityVerbs = {
  TASK_CREATED: 'TASK_CREATED',
  TASK_UPDATED: 'TASK_UPDATED',
  TASK_STATUS_CHANGED: 'TASK_STATUS_CHANGED',
  TASK_ARCHIVED: 'TASK_ARCHIVED',
  TASK_ACCEPTED: 'TASK_ACCEPTED',
  TASK_ACCEPTANCE_REVERTED: 'TASK_ACCEPTANCE_REVERTED',
  TASKS_ACCEPTED: 'TASKS_ACCEPTED',
  TASK_RESTORED: 'TASK_RESTORED',
  TASK_DELETED: 'TASK_DELETED',
  TASK_COMMENT_CREATED: 'TASK_COMMENT_CREATED',
  TASK_COMMENT_UPDATED: 'TASK_COMMENT_UPDATED',
  TASK_COMMENT_DELETED: 'TASK_COMMENT_DELETED',
  TIME_LOG_CREATED: 'TIME_LOG_CREATED',
  CLIENT_CREATED: 'CLIENT_CREATED',
  CLIENT_UPDATED: 'CLIENT_UPDATED',
  CLIENT_ARCHIVED: 'CLIENT_ARCHIVED',
  CLIENT_RESTORED: 'CLIENT_RESTORED',
  CLIENT_DELETED: 'CLIENT_DELETED',
  CONTACT_CREATED: 'CONTACT_CREATED',
  CONTACT_UPDATED: 'CONTACT_UPDATED',
  CONTACT_ARCHIVED: 'CONTACT_ARCHIVED',
  CONTACT_RESTORED: 'CONTACT_RESTORED',
  CONTACT_DELETED: 'CONTACT_DELETED',
  CONTACT_INVITED_TO_PORTAL: 'CONTACT_INVITED_TO_PORTAL',
  PROJECT_CREATED: 'PROJECT_CREATED',
  PROJECT_UPDATED: 'PROJECT_UPDATED',
  PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',
  PROJECT_RESTORED: 'PROJECT_RESTORED',
  PROJECT_DELETED: 'PROJECT_DELETED',
  HOUR_BLOCK_CREATED: 'HOUR_BLOCK_CREATED',
  HOUR_BLOCK_UPDATED: 'HOUR_BLOCK_UPDATED',
  HOUR_BLOCK_ARCHIVED: 'HOUR_BLOCK_ARCHIVED',
  HOUR_BLOCK_RESTORED: 'HOUR_BLOCK_RESTORED',
  HOUR_BLOCK_DELETED: 'HOUR_BLOCK_DELETED',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_ARCHIVED: 'USER_ARCHIVED',
  USER_RESTORED: 'USER_RESTORED',
  USER_DELETED: 'USER_DELETED',
  CLIENT_VIEWED: 'CLIENT_VIEWED',
  PROJECT_VIEWED: 'PROJECT_VIEWED',
  OAUTH_CONNECTED: 'OAUTH_CONNECTED',
  OAUTH_DISCONNECTED: 'OAUTH_DISCONNECTED',
  OAUTH_REFRESHED: 'OAUTH_REFRESHED',
  OAUTH_EXPIRED: 'OAUTH_EXPIRED',
  TASK_CREATED_FROM_EMAIL: 'TASK_CREATED_FROM_EMAIL',
  TASK_CREATED_FROM_SUGGESTION: 'TASK_CREATED_FROM_SUGGESTION',
  TASK_SUGGESTION_REJECTED: 'TASK_SUGGESTION_REJECTED',
  TASK_SUGGESTION_RESTORED: 'TASK_SUGGESTION_RESTORED',
  GITHUB_REPO_LINKED: 'GITHUB_REPO_LINKED',
  GITHUB_REPO_UNLINKED: 'GITHUB_REPO_UNLINKED',
  GITHUB_PR_CREATED: 'GITHUB_PR_CREATED',
  INTEGRATION_PROJECT_LINKED: 'INTEGRATION_PROJECT_LINKED',
  INTEGRATION_PROJECT_UNLINKED: 'INTEGRATION_PROJECT_UNLINKED',
  PR_SUGGESTION_CREATED: 'PR_SUGGESTION_CREATED',
  PR_SUGGESTION_APPROVED: 'PR_SUGGESTION_APPROVED',
  PR_SUGGESTION_REJECTED: 'PR_SUGGESTION_REJECTED',
  PR_CREATED_FROM_SUGGESTION: 'PR_CREATED_FROM_SUGGESTION',
  // Proposal events
  PROPOSAL_CREATED: 'PROPOSAL_CREATED',
  PROPOSAL_SENT: 'PROPOSAL_SENT',
  PROPOSAL_VIEWED: 'PROPOSAL_VIEWED',
  PROPOSAL_ACCEPTED: 'PROPOSAL_ACCEPTED',
  PROPOSAL_REJECTED: 'PROPOSAL_REJECTED',
  PROPOSAL_COUNTERSIGNED: 'PROPOSAL_COUNTERSIGNED',
  PROPOSAL_UPDATED: 'PROPOSAL_UPDATED',
  PROPOSAL_SHARED: 'PROPOSAL_SHARED',
  PROPOSAL_UNSHARED: 'PROPOSAL_UNSHARED',
  PROPOSAL_ARCHIVED: 'PROPOSAL_ARCHIVED',
  PROPOSAL_RESTORED: 'PROPOSAL_RESTORED',
  // Invoice events
  INVOICE_CREATED: 'INVOICE_CREATED',
  INVOICE_UPDATED: 'INVOICE_UPDATED',
  INVOICE_SENT: 'INVOICE_SENT',
  INVOICE_UNSENT: 'INVOICE_UNSENT',
  INVOICE_VIEWED: 'INVOICE_VIEWED',
  INVOICE_PAID: 'INVOICE_PAID',
  INVOICE_VOIDED: 'INVOICE_VOIDED',
  INVOICE_SHARED: 'INVOICE_SHARED',
  INVOICE_UNSHARED: 'INVOICE_UNSHARED',
  INVOICE_ARCHIVED: 'INVOICE_ARCHIVED',
  INVOICE_RESTORED: 'INVOICE_RESTORED',
  INVOICE_DELETED: 'INVOICE_DELETED',
  // Lead events
  LEAD_CREATED: 'LEAD_CREATED',
  LEAD_UPDATED: 'LEAD_UPDATED',
  LEAD_STATUS_CHANGED: 'LEAD_STATUS_CHANGED',
  LEAD_SCORED: 'LEAD_SCORED',
  LEAD_PRIORITY_CHANGED: 'LEAD_PRIORITY_CHANGED',
  LEAD_CONVERTED: 'LEAD_CONVERTED',
  LEAD_ARCHIVED: 'LEAD_ARCHIVED',
  LEAD_RESTORED: 'LEAD_RESTORED',
  LEAD_UPDATE_LOGGED: 'LEAD_UPDATE_LOGGED',
  LEAD_SUGGESTION_APPROVED: 'LEAD_SUGGESTION_APPROVED',
  LEAD_SUGGESTION_DISMISSED: 'LEAD_SUGGESTION_DISMISSED',
  // Submission events
  SUBMISSION_ACKNOWLEDGED: 'SUBMISSION_ACKNOWLEDGED',
  SUBMISSION_UNACKNOWLEDGED: 'SUBMISSION_UNACKNOWLEDGED',
  SUBMISSION_ARCHIVED: 'SUBMISSION_ARCHIVED',
  SUBMISSION_RESTORED: 'SUBMISSION_RESTORED',
  SUBMISSION_DESTROYED: 'SUBMISSION_DESTROYED',
  // Worker deployment events
  WORKER_PLAN_REQUESTED: 'WORKER_PLAN_REQUESTED',
  WORKER_IMPLEMENT_REQUESTED: 'WORKER_IMPLEMENT_REQUESTED',
  WORKER_CANCELLED: 'WORKER_CANCELLED',
  // Monthly close events
  MONTHLY_CLOSE_CLOSED: 'MONTHLY_CLOSE_CLOSED',
  MONTHLY_CLOSE_REOPENED: 'MONTHLY_CLOSE_REOPENED',
} as const

export type ActivityVerb = (typeof ActivityVerbs)[keyof typeof ActivityVerbs]

export type ActivityQueryFilters = {
  targetType?: ActivityTargetType | ActivityTargetType[]
  targetId?: string
  projectId?: string
  clientId?: string
  includeDeleted?: boolean
  cursor?: string
  limit?: number
}

export type ActivityQueryResult = {
  logs: ActivityLogWithActor[]
  hasMore: boolean
  nextCursor: string | null
}

export type ActivityEvent = {
  verb: ActivityVerb
  summary: string
  metadata?: Json
}
