import type { ActivitySourceValue, UserRoleValue } from '@/lib/types'
import type { Json } from '@/lib/types/json'

type DbActivityLog = {
  id: string
  actor_id: string | null
  actor_role: UserRoleValue | null
  source: ActivitySourceValue
  verb: string
  summary: string
  target_type: string
  target_id: string | null
  target_client_id: string | null
  target_project_id: string | null
  context_route: string | null
  metadata: Json
  created_at: string
}

export type ActivityReferenceUser = {
  name: string
  avatarUrl: string | null
}

/**
 * Display names for the raw ids stored in metadata (owners, assignees,
 * contacts, projects). Attached per page by the activity query so the feed
 * never has to render a UUID.
 */
export type ActivityReferences = {
  users: Record<string, ActivityReferenceUser>
  contacts: Record<string, string>
  projects: Record<string, string>
}

export type ActivityLogWithActor = DbActivityLog & {
  actor?: {
    id: string
    full_name: string | null
    email: string
    avatar_url: string | null
  } | null
  references?: ActivityReferences
}

export const ACTIVITY_TARGET_TYPES = [
  'TASK',
  'PROJECT',
  'CLIENT',
  'CONTACT',
  'LEAD',
  'SUBMISSION',
  'COMMENT',
  'TIME_LOG',
  'HOUR_BLOCK',
  'INVOICE',
  'MONTHLY_CLOSE',
  'USER',
  'SETTINGS',
  'CLIENT_UPDATE',
  'PLAN',
] as const

export type ActivityTargetType = (typeof ACTIVITY_TARGET_TYPES)[number]

/**
 * Every verb a writer may emit. Verbs are stored as text, so historical rows
 * for retired verbs (page views, the removed proposals feature, task/PR
 * suggestions) still render through the feed's string-based fallbacks; they
 * are simply no longer part of the writable vocabulary.
 */
export const ActivityVerbs = {
  // Tasks
  TASK_CREATED: 'TASK_CREATED',
  TASK_UPDATED: 'TASK_UPDATED',
  TASK_STATUS_CHANGED: 'TASK_STATUS_CHANGED',
  TASK_ARCHIVED: 'TASK_ARCHIVED',
  TASK_ACCEPTED: 'TASK_ACCEPTED',
  TASK_ACCEPTANCE_REVERTED: 'TASK_ACCEPTANCE_REVERTED',
  TASKS_ACCEPTED: 'TASKS_ACCEPTED',
  TASK_RESTORED: 'TASK_RESTORED',
  TASK_DELETED: 'TASK_DELETED',
  TASK_COMMENT_CREATED: 'TASK_COMMENT_CREATED',
  TASK_COMMENT_UPDATED: 'TASK_COMMENT_UPDATED',
  TASK_COMMENT_DELETED: 'TASK_COMMENT_DELETED',
  TASK_ATTACHMENT_ADDED: 'TASK_ATTACHMENT_ADDED',
  TASK_ATTACHMENT_REMOVED: 'TASK_ATTACHMENT_REMOVED',
  TASK_WORKER_STATUS_CHANGED: 'TASK_WORKER_STATUS_CHANGED',
  WORKER_PLAN_REQUESTED: 'WORKER_PLAN_REQUESTED',
  WORKER_CANCELLED: 'WORKER_CANCELLED',
  // Planning
  PLANNING_SESSION_CREATED: 'PLANNING_SESSION_CREATED',
  PLAN_REVISION_CREATED: 'PLAN_REVISION_CREATED',
  // Time logs
  TIME_LOG_CREATED: 'TIME_LOG_CREATED',
  TIME_LOG_UPDATED: 'TIME_LOG_UPDATED',
  TIME_LOG_DELETED: 'TIME_LOG_DELETED',
  // Clients
  CLIENT_CREATED: 'CLIENT_CREATED',
  CLIENT_UPDATED: 'CLIENT_UPDATED',
  CLIENT_ARCHIVED: 'CLIENT_ARCHIVED',
  CLIENT_RESTORED: 'CLIENT_RESTORED',
  CLIENT_DELETED: 'CLIENT_DELETED',
  // Client updates (outbound emails)
  CLIENT_UPDATE_DRAFTED: 'CLIENT_UPDATE_DRAFTED',
  CLIENT_UPDATE_EDITED: 'CLIENT_UPDATE_EDITED',
  CLIENT_UPDATE_SENT: 'CLIENT_UPDATE_SENT',
  // Contacts
  CONTACT_CREATED: 'CONTACT_CREATED',
  CONTACT_UPDATED: 'CONTACT_UPDATED',
  CONTACT_ARCHIVED: 'CONTACT_ARCHIVED',
  CONTACT_RESTORED: 'CONTACT_RESTORED',
  CONTACT_DELETED: 'CONTACT_DELETED',
  CONTACT_INVITED_TO_PORTAL: 'CONTACT_INVITED_TO_PORTAL',
  CONTACT_CLIENT_LINKED: 'CONTACT_CLIENT_LINKED',
  CONTACT_CLIENT_UNLINKED: 'CONTACT_CLIENT_UNLINKED',
  // Projects
  PROJECT_CREATED: 'PROJECT_CREATED',
  PROJECT_UPDATED: 'PROJECT_UPDATED',
  PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',
  PROJECT_RESTORED: 'PROJECT_RESTORED',
  PROJECT_DELETED: 'PROJECT_DELETED',
  GITHUB_REPO_LINKED: 'GITHUB_REPO_LINKED',
  GITHUB_REPO_UNLINKED: 'GITHUB_REPO_UNLINKED',
  INTEGRATION_PROJECT_LINKED: 'INTEGRATION_PROJECT_LINKED',
  INTEGRATION_PROJECT_UNLINKED: 'INTEGRATION_PROJECT_UNLINKED',
  // Hour blocks
  HOUR_BLOCK_CREATED: 'HOUR_BLOCK_CREATED',
  HOUR_BLOCK_UPDATED: 'HOUR_BLOCK_UPDATED',
  HOUR_BLOCK_ARCHIVED: 'HOUR_BLOCK_ARCHIVED',
  HOUR_BLOCK_RESTORED: 'HOUR_BLOCK_RESTORED',
  HOUR_BLOCK_DELETED: 'HOUR_BLOCK_DELETED',
  // Users
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_ARCHIVED: 'USER_ARCHIVED',
  USER_RESTORED: 'USER_RESTORED',
  USER_DELETED: 'USER_DELETED',
  USER_PASSWORD_CHANGED: 'USER_PASSWORD_CHANGED',
  OAUTH_CONNECTED: 'OAUTH_CONNECTED',
  OAUTH_DISCONNECTED: 'OAUTH_DISCONNECTED',
  // Invoices
  INVOICE_CREATED: 'INVOICE_CREATED',
  INVOICE_UPDATED: 'INVOICE_UPDATED',
  INVOICE_SENT: 'INVOICE_SENT',
  INVOICE_UNSENT: 'INVOICE_UNSENT',
  INVOICE_VIEWED: 'INVOICE_VIEWED',
  INVOICE_PAID: 'INVOICE_PAID',
  INVOICE_VOIDED: 'INVOICE_VOIDED',
  INVOICE_SHARED: 'INVOICE_SHARED',
  INVOICE_UNSHARED: 'INVOICE_UNSHARED',
  INVOICE_ARCHIVED: 'INVOICE_ARCHIVED',
  INVOICE_RESTORED: 'INVOICE_RESTORED',
  INVOICE_DELETED: 'INVOICE_DELETED',
  // Invoice settings
  PRODUCT_CATALOG_ITEM_CREATED: 'PRODUCT_CATALOG_ITEM_CREATED',
  PRODUCT_CATALOG_ITEM_UPDATED: 'PRODUCT_CATALOG_ITEM_UPDATED',
  TAX_RATE_CREATED: 'TAX_RATE_CREATED',
  TAX_RATE_UPDATED: 'TAX_RATE_UPDATED',
  // Leads
  LEAD_CREATED: 'LEAD_CREATED',
  LEAD_UPDATED: 'LEAD_UPDATED',
  LEAD_STATUS_CHANGED: 'LEAD_STATUS_CHANGED',
  LEAD_CONVERTED: 'LEAD_CONVERTED',
  LEAD_ARCHIVED: 'LEAD_ARCHIVED',
  LEAD_RESTORED: 'LEAD_RESTORED',
  LEAD_DELETED: 'LEAD_DELETED',
  LEAD_UPDATE_LOGGED: 'LEAD_UPDATE_LOGGED',
  LEAD_UPDATE_EDITED: 'LEAD_UPDATE_EDITED',
  LEAD_UPDATE_DELETED: 'LEAD_UPDATE_DELETED',
  // Submissions
  SUBMISSION_RECEIVED: 'SUBMISSION_RECEIVED',
  SUBMISSION_ACKNOWLEDGED: 'SUBMISSION_ACKNOWLEDGED',
  SUBMISSION_UNACKNOWLEDGED: 'SUBMISSION_UNACKNOWLEDGED',
  SUBMISSION_ARCHIVED: 'SUBMISSION_ARCHIVED',
  SUBMISSION_RESTORED: 'SUBMISSION_RESTORED',
  SUBMISSION_DESTROYED: 'SUBMISSION_DESTROYED',
  SUBMISSIONS_ABANDONED: 'SUBMISSIONS_ABANDONED',
  // Monthly close
  MONTHLY_CLOSE_CLOSED: 'MONTHLY_CLOSE_CLOSED',
  MONTHLY_CLOSE_RECLOSED: 'MONTHLY_CLOSE_RECLOSED',
  MONTHLY_CLOSE_REOPENED: 'MONTHLY_CLOSE_REOPENED',
} as const

export type ActivityVerb = (typeof ActivityVerbs)[keyof typeof ActivityVerbs]

export type ActivityQueryFilters = {
  targetType?: ActivityTargetType | ActivityTargetType[]
  targetId?: string
  projectId?: string
  clientId?: string
  cursor?: string
  limit?: number
}

export type ActivityQueryResult = {
  logs: ActivityLogWithActor[]
  hasMore: boolean
  nextCursor: string | null
}

export type ActivityEvent = {
  verb: ActivityVerb
  summary: string
  metadata?: Json
}
